name: Verify Dockerfile Presence

on:
  push:
    branches: [main]

jobs:
  check-dockerfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files for debugging
        run: ls -al

      - name: Verify Dockerfile exists
        run: |
          if [ -f Dockerfile ]; then echo "Dockerfile exists"; else echo "Dockerfile does not exist"; exit 1; fi
